[package]
name = "fltk-webview"
version = "0.2.6"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"
description = "Webview for embedded fltk windows"
repository = "https://github.com/fltk-rs/webview"
documentation = "https://docs.rs/fltk-webview"
keywords = ["gui", "widgets", "bindings", "graphics", "webview"]
categories = ["gui"]
readme = "README.md"
license = "MIT"

[dependencies]
fltk = "1.1"

[build-dependencies]
pkg-config = "0.3"
cc = "1"

# for the example
[dev-dependencies]
pulldown-cmark = "0.8"