[package]
name = "fltk-webview"
version = "0.2.10"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"
description = "Webview for embedded fltk windows"
repository = "https://github.com/fltk-rs/fltk-webview"
documentation = "https://docs.rs/fltk-webview"
keywords = ["gui", "widgets", "bindings", "graphics", "webview"]
categories = ["gui"]
readme = "README.md"
license = "MIT"

[dependencies]
fltk = "1.1"
fltk-webview-sys = { version = "0.2.8", path = "fltk-webview-sys" }

# for the examples
[dev-dependencies]
pulldown-cmark = "0.8"
tinyjson = "2"