[package]
name = "fltk-webview"
version = "0.1.1"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"
description = "Webview for embedded fltk windows"
repository = "https://github.com/MoAlyousef/webview"
documentation = "https://docs.rs/fltk-webview"
keywords = ["gui", "widgets", "bindings", "graphics", "webview"]
categories = ["gui"]
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1"
webview-official-sys = "0.1.2"

[target.'cfg(target_os = "linux")'.dependencies]
gdkx11-sys = "0.10"
gtk-sys = "0.10"
gdk-sys = "0.10"