[package]
name = "fltk-webview"
version = "0.1.11"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"
description = "Webview for embedded fltk windows"
repository = "https://github.com/fltk-rs/webview"
documentation = "https://docs.rs/fltk-webview"
keywords = ["gui", "widgets", "bindings", "graphics", "webview"]
categories = ["gui"]
readme = "README.md"
license = "MIT"

[dependencies]
fltk = "1.1"
webview-official-sys = "0.1.2"

[build-dependencies]
cc = "1"
